services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile.bot
    ports:
      - "2333:2333"  # Lavalink port
    volumes:
      - ./musicbot:/app/musicbot
      - ./logs:/app/logs
      - ./plugins:/app/plugins
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped