x-bot-env: &bot-env
  PYTHONUNBUFFERED: 1
  TZ: Asia/Seoul
  LAVALINK_HOST: lavalink
  LAVALINK_PASSWORD: youshallnotpass
  SHARD_COUNT: 2
  REDIS_HOST: redis

x-bot-base: &bot-base
  build:
    context: .
    dockerfile: tapi/Dockerfile.bot
  restart: unless-stopped
  volumes:
    - ./tapi:/app/tapi
    - ./plugins:/app/plugins
  deploy:
    resources:
      limits:
        cpus: '0.8'
        memory: 512M

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.1.1
    container_name: lavalink
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./plugins:/opt/Lavalink/plugins
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--header=Authorization: youshallnotpass", "http://localhost:2333/v4/info"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bot-shard-0:
    <<: *bot-base
    container_name: bot-shard-0
    environment:
      <<: *bot-env
      SHARD_ID: 0
    volumes:
      - ./tapi:/app/tapi
      - ./plugins:/app/plugins

    depends_on:
      lavalink:
        condition: service_healthy
      redis:
        condition: service_started

  bot-shard-1:
    <<: *bot-base
    container_name: bot-shard-1
    environment:
      <<: *bot-env
      SHARD_ID: 1
    volumes:
      - ./tapi:/app/tapi
      - ./plugins:/app/plugins
    depends_on:
      lavalink:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 900 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    sysctls:
      - vm.overcommit_memory=1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
