services:
  bot:
    build: 
      context: ./musicbot
      dockerfile: Dockerfile.bot
    ports:
      - "2333:2333"  # Lavalink port
    volumes:
      - ./musicbot:/app/musicbot
      - ./logs:/app/logs
      - ./plugins:/app/plugins
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"  # Streamlit port
    volumes:
      - ./musicbot:/app/musicbot  # Share the same database with the bot
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
    depends_on:
      - bot
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_TOKEN_ROTATION_INTERVAL_MINUTES=1440
      - GF_SESSION_LIFETIME=24h
    depends_on:
      - prometheus
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

  music-bot-exporter:
    build:
      context: ./exporter
      dockerfile: Dockerfile.exporter
    container_name: music-bot-exporter
    ports:
      - "8000:8000"
    volumes:
      - ./musicbot/db:/app/musicbot/db
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data: