version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile.bot
    ports:
      - "2333:2333"  # Lavalink port
    volumes:
      - ./musicbot:/app/musicbot
      - ./logs:/app/logs
      - ./plugins:/app/plugins
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"  # Streamlit port
    volumes:
      - ./musicbot:/app/musicbot  # Share the same database with the bot
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - bot
    restart: unless-stopped