global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "music_bot"
    static_configs:
      - targets: ["music-bot-exporter:8000"]
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: /metrics
